import { EntityTestProvider, ProviderConfig } from '@ulmax/testing';
import { Emergency } from '../models/emergency.entity';
import { EmergencyService } from './emergency.service';

describe('General Public autogenerated providers', () => {
    const configs: Array<ProviderConfig<any>> = [
        { entity: Emergency, provider: EmergencyService },
    ];
    configs.forEach((cfg) => new EntityTestProvider(cfg).test());
});
