import { ControllerConfig, EntityTestController } from '@eagle/testing';
import { AdmissionController } from './admission.controller';
import { AdmissionService } from '../services/admission.service';
import { ConsultationController } from './consultation.controller';
import { ConsultationService } from '../services/consultation.service';
import { InstitutionController } from './institution.controller';
import { InstitutionService } from '../services/institution.service';
import { LabTestController } from './LabTest.controller';
import { LabTestService } from '../services/LabTest.service';
import { PrescriptionController } from './prescription.controller';
import { PrescriptionService } from '../services/prescription.service';
import { ReviewController } from './review.controller';
import { ReviewService } from '../services/review.service';
import { StaffController } from './staff.controller';
import { StaffService } from '../services/staff.service';

describe('EHR autogenerated Controllers', () => {
    const configs: ControllerConfig[] = [
        { controller: AdmissionController, provider: AdmissionService },
        { controller: ConsultationController, provider: ConsultationService },
        { controller: InstitutionController, provider: InstitutionService },
        { controller: LabTestController, provider: LabTestService },
        { controller: PrescriptionController, provider: PrescriptionService },
        { controller: ReviewController, provider: ReviewService },
        { controller: StaffController, provider: StaffService },
    ];

    configs.forEach((cfg) => new EntityTestController(cfg).test());
});
