import { EntityTestProvider, ProviderConfig } from '@ulmax/testing';
import { Admission } from '../admission/admission.entity';
import { AdmissionService } from '../admission/admission.service';
import { Consultation } from '../consultation/consultation.entity';
import { ConsultationService } from '../consultation/consultation.service';
import { Institution } from '../institution/institution.entity';
import { InstitutionService } from '../institution/institution.service';
import { LabTest } from '../labtest/labtest.entity';
import { LabTestService } from '../labtest/labtest.service';
import { Prescription } from '../prescription/prescription.entity';
import { PrescriptionService } from '../prescription/prescription.service';
import { Review } from '../review/review.entity';
import { ReviewService } from '../review/review.service';
import { Staff } from '../staff/staff.entity';
import { StaffService } from '../staff/staff.service';

describe('EHR autogenerated providers', () => {

    const configs: Array<ProviderConfig<any>> = [
        { entity: Admission, provider: AdmissionService },
        { entity: Consultation, provider: ConsultationService },
        { entity: Institution, provider: InstitutionService },
        { entity: LabTest, provider: LabTestService },
        { entity: Prescription, provider: PrescriptionService },
        { entity: Review, provider: ReviewService },
        { entity: Staff, provider: StaffService },
    ];

    configs.forEach((cfg) => new EntityTestProvider(cfg).test());
});
