import { ApiModelProperty } from '@nestjs/swagger';
import { BaseModel } from '@ulmax/server-shared';
import { IsDefined } from 'class-validator';
import { Column, CreateDateColumn, Entity, PrimaryGeneratedColumn, UpdateDateColumn } from 'typeorm';

@Entity()
export class Comment implements BaseModel {
  /**`
   * autogenerated id for the comment
   */
  @IsDefined()
  @ApiModelProperty()
  @PrimaryGeneratedColumn('uuid')
  id: string;

  /**
   * The comment's author trackingId
   */
  @IsDefined()
  @ApiModelProperty()
  @Column()
  authorId: string;

  /**
   * the comment text
   */
  @IsDefined()
  @Column()
  @ApiModelProperty()
  text: string;

  /**
   * the comment text
   */
  @IsDefined()
  @Column()
  @ApiModelProperty()
  postId: string;

  @CreateDateColumn()
  createdAt?: Date;

  @UpdateDateColumn()
  updatedAt?: Date;
}
