import { BaseModel } from '@eagle/server-shared';
import { ApiModelProperty } from '@nestjs/swagger';
import { IsDefined } from 'class-validator';
import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm';

@Entity()
export class Comment extends BaseModel {
  /**`
   * autogenerated id for the comment
   */
  @IsDefined()
  @ApiModelProperty()
  @PrimaryGeneratedColumn('uuid')
  id: string;

  /**
   * The comment's author trackingId
   */
  @IsDefined()
  @ApiModelProperty()
  @Column()
  authorId: string;

  /**
   * the comment text
   */
  @IsDefined()
  @Column()
  @ApiModelProperty()
  text: string;

  /**
   * the comment text
   */
  @IsDefined()
  @Column()
  @ApiModelProperty()
  postId: string;
}
