import { PrimaryGeneratedColumn, Column, Entity } from 'typeorm';
import { IsDefined } from 'class-validator';
import { BaseModel } from '@eagle/server-shared';
import { ApiModelProperty } from '@nestjs/swagger';

/**
 * Posts model for SIP
 */
@Entity()
export class Post extends BaseModel {
  /**
   * the unique autogenerated ID
   */
  @IsDefined()
  @PrimaryGeneratedColumn('uuid')
  @ApiModelProperty()
  id: string;

  /**
   * The title for the post
   */
  @IsDefined()
  @Column('varchar')
  @ApiModelProperty()
  title: string;

  /**
   * A brief summary of the post
   */
  @IsDefined()
  @Column('varchar')
  @ApiModelProperty()
  subtitle: string;

  /**
   * The iage displayed like a billboard for the post
   */
  @IsDefined()
  @Column('varchar')
  @ApiModelProperty()
  image: string;

  /**
   * The post actual full text
   */
  @IsDefined()
  @Column('varchar')
  @ApiModelProperty()
  text: string;

  /**
   * The author's trackingId
   */
  @IsDefined()
  @Column('varchar')
  @ApiModelProperty()
  authorId: string;
}
