import { ApiModelProperty } from '@nestjs/swagger';
import { BaseModel } from '@ulmax/server-shared';
import { IsDefined } from 'class-validator';
import {
  Column,
  CreateDateColumn,
  Entity,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm';

/**
 * Posts model for SIP
 */
@Entity()
export class Post implements BaseModel {
  /**
   * the unique autogenerated ID
   */
  @IsDefined()
  @PrimaryGeneratedColumn('uuid')
  @ApiModelProperty()
  id: string;

  /**
   * The title for the post
   */
  @IsDefined()
  @Column()
  @ApiModelProperty()
  title: string;

  /**
   * A brief summary of the post
   */
  @IsDefined()
  @Column()
  @ApiModelProperty()
  subtitle: string;

  /**
   * The iage displayed like a billboard for the post
   */
  @IsDefined()
  @Column()
  @ApiModelProperty()
  image: string;

  /**
   * The post actual full text
   */
  @IsDefined()
  @Column()
  @ApiModelProperty()
  text: string;

  /**
   * The author's trackingId
   */
  @IsDefined()
  @Column()
  @ApiModelProperty()
  authorId: string;

  @CreateDateColumn()
  createdAt?: Date;

  @UpdateDateColumn()
  updatedAt?: Date;
}
